Got default URI handling in Linux!  (GNOME, at least)
Just gotta do a little cleaning up and then repeat in Windows!

diff --git a/dpkgfiles/postrm b/dpkgfiles/postrm
--- a/dpkgfiles/postrm
+++ b/dpkgfiles/postrm
@@ -1,9 +1,31 @@
-#!/bin/sh
+#! /usr/bin/python
+
+import os
+from subprocess import Popen, PIPE
+
+def execAndWait(cli_str):
+   process = Popen(cli_str, shell=True)
+   while process.poll() == None:
+      time.sleep(0.01)
+
+execAndWait('xdg-desktop-menu  uninstall /usr/share/applications/armory.desktop')
+execAndWait('xdg-desktop-menu  uninstall /usr/share/applications/armorytestnet.desktop')
+execAndWait('xdg-desktop-menu  uninstall /usr/share/applications/armoryoffline.desktop')
+execAndWait('xdg-icon-resource uninstall --size 64 armoryicon')
+execAndWait('xdg-icon-resource uninstall --size 64 armorytestneticon')
+
+execAndWait('gconftool-2 --unset /desktop/gnome/url-handlers/bitcoin/command')
+execAndWait('gconftool-2 -t bool -s /desktop/gnome/url-handlers/bitcoin/enabled false')
+
+# ACR: REMOVED DEFAULT POSTINST TEMPLATE FROM dh_make
+#      ...
+
 # postrm script for armory
 #
 # see: dh_installdeb(1)
 
-set -e
+
+#set -e
 
 # summary of how this script can be called:
 #        * <postrm> `remove'
@@ -19,24 +41,19 @@ set -e
 # the debian-policy package
 
 
-case "$1" in
-    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-    ;;
-
-    *)
-        echo "postrm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
-
+#case "$1" in
+    #purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    #;;
+#
+    #*)
+        #echo "postrm called with unknown argument \`$1'" >&2
+        #exit 1
+    #;;
+#esac
+#
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 
 #DEBHELPER#
-xdg-desktop-menu  uninstall /usr/share/applications/armory.desktop
-xdg-desktop-menu  uninstall /usr/share/applications/armorytestnet.desktop
-xdg-desktop-menu  uninstall /usr/share/applications/armoryoffline.desktop
-xdg-icon-resource uninstall --size 64 armoryicon
-xdg-icon-resource uninstall --size 64 armorytestneticon
 
 exit 0
